// <auto-generated />
using System;
using BlackJack.API.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlackJack.API.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlackJack.Domain.Entities.Card", b =>
                {
                    b.Property<int>("Suit")
                        .HasColumnType("integer");

                    b.Property<int>("Value")
                        .HasColumnType("integer");

                    b.Property<Guid?>("DealerId")
                        .HasColumnType("uuid");

                    b.Property<string>("ImageName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsVisible")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("PlayerId")
                        .HasColumnType("uuid");

                    b.HasKey("Suit", "Value");

                    b.HasIndex("DealerId");

                    b.HasIndex("PlayerId");

                    b.ToTable("card");
                });

            modelBuilder.Entity("BlackJack.Domain.Entities.Dealer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CardDeckId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsStand")
                        .HasColumnType("boolean");

                    b.HasKey("Id");

                    b.HasIndex("CardDeckId");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("dealer");
                });

            modelBuilder.Entity("BlackJack.Domain.Entities.Deck", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("GameId")
                        .IsUnique();

                    b.ToTable("deck");
                });

            modelBuilder.Entity("BlackJack.Domain.Entities.GameSession", b =>
                {
                    b.Property<Guid>("GameId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CurrentPlayerIndex")
                        .HasColumnType("integer");

                    b.Property<Guid>("DealerId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("DeckId")
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PlayersCount")
                        .HasColumnType("integer");

                    b.HasKey("GameId");

                    b.HasIndex("DealerId");

                    b.HasIndex("DeckId");

                    b.ToTable("game");
                });

            modelBuilder.Entity("BlackJack.Domain.Entities.Player", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("GameId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IsStand")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("GameId");

                    b.ToTable("player");
                });

            modelBuilder.Entity("BlackJack.Domain.Entities.Card", b =>
                {
                    b.HasOne("BlackJack.Domain.Entities.Dealer", null)
                        .WithMany("Cards")
                        .HasForeignKey("DealerId");

                    b.HasOne("BlackJack.Domain.Entities.Player", null)
                        .WithMany("Cards")
                        .HasForeignKey("PlayerId");
                });

            modelBuilder.Entity("BlackJack.Domain.Entities.Dealer", b =>
                {
                    b.HasOne("BlackJack.Domain.Entities.Deck", "CardDeck")
                        .WithMany()
                        .HasForeignKey("CardDeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlackJack.Domain.Entities.GameSession", "GameSession")
                        .WithOne()
                        .HasForeignKey("BlackJack.Domain.Entities.Dealer", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardDeck");

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("BlackJack.Domain.Entities.Deck", b =>
                {
                    b.HasOne("BlackJack.Domain.Entities.GameSession", "GameSession")
                        .WithOne()
                        .HasForeignKey("BlackJack.Domain.Entities.Deck", "GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("BlackJack.Domain.Entities.GameSession", b =>
                {
                    b.HasOne("BlackJack.Domain.Entities.Dealer", "Dealer")
                        .WithMany()
                        .HasForeignKey("DealerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BlackJack.Domain.Entities.Deck", "Deck")
                        .WithMany()
                        .HasForeignKey("DeckId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dealer");

                    b.Navigation("Deck");
                });

            modelBuilder.Entity("BlackJack.Domain.Entities.Player", b =>
                {
                    b.HasOne("BlackJack.Domain.Entities.GameSession", "GameSession")
                        .WithMany("Players")
                        .HasForeignKey("GameId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GameSession");
                });

            modelBuilder.Entity("BlackJack.Domain.Entities.Dealer", b =>
                {
                    b.Navigation("Cards");
                });

            modelBuilder.Entity("BlackJack.Domain.Entities.GameSession", b =>
                {
                    b.Navigation("Players");
                });

            modelBuilder.Entity("BlackJack.Domain.Entities.Player", b =>
                {
                    b.Navigation("Cards");
                });
#pragma warning restore 612, 618
        }
    }
}
